mode: aspect_finetune
model: BERT

device: 0
data_path: data/iSA
model_path: results/iSA
train_file: iSA_Train_v2_Implicit_Labeled_preprocess_finetune.pkl
test_file: iSA_Test_Gold_Implicit_Labeled_preprocess_finetune.pkl
num_workers_per_loader: 2

seed: 42
batch_size: 32
dropout: 0.1
epoch: 6
warm_up: 70
label_smooth: 0.01

optimizer: adamw
learning_rate: 0.00005
weight_decay: 0.015
grad_norm: 5.0


ckpt: '/Users/jordanharris/SCAPT-ABSA/checkpoints/restaurants_BERT/last.ckpt'
state_dict: '/Users/jordanharris/SCAPT-ABSA/results/restaurants/BERT_0714051910/epoch_0_step_112_acc_0.8696_f1_0.7974_loss_0.5574.pt'
