mode: aspect_finetune
model: TransEnc

device: 0
data_path: data/MAMS
model_path: results/MAMS
train_file: train_preprocess_finetune.pkl
test_file: test_preprocess_finetune.pkl
num_workers_per_loader: 16

seed: 42
batch_size: 32
dropout: 0.1
epoch: 20
warm_up: 100
label_smooth: 0.1

head_size: 6
layers: 6
hidden_size: 300
feedforward: 1200
dense_hidden_size: 100

optimizer: adamw
learning_rate: 0.0001
weight_decay: 0.015
grad_norm: 5.0
