mode: preprocess_finetune
base_path: data/restaurants

train_file: Restaurants_Train_v2_Implicit_Labeled.xml 
test_file: Restaurants_Test_Gold_Implicit_Labeled.xml

lowercase: True
remove_list:
  - conflict
